#!/bin/sh

set -e
umask 0002

OPTIONS="--polar disabled \
         --polar relaxed \
         --polar relaxed-headers"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  if test -f "disabled.bin"; then
    /usr/bin/sudo /usr/bin/systemctl --quiet disable opendmarc.service
    if systemctl is-active --quiet opendmarc-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop opendmarc.service
    else
      echo "dmarc will be disabled on next reboot."
    fi
  else
    /usr/bin/sudo /usr/bin/systemctl --quiet enable opendmarc.service
    if systemctl is-active --quiet opendmarc-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart opendmarc-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart opendmarc.service
    else
      echo "dmarc will be enabled on next reboot."
    fi
  fi

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

